### ISSUE TITLE
Error run JSNAP by crontab

### ISSUE THREAD

**Issue by ngocthach** [Juniper/juise#36]
Dear all,
I use JSNAP to check some divices, I set crontab to run script

Log:
which: no juise in (/usr/bin:/bin)
ERROR: could not find 'juise' in your PATH

But I check PATH. It's ok
# which juise
/usr/jawa/bin/juise

Thank for your reply

**Comment by philshafer** [comment]
I’m guessing your cron job is running with a different PATH than your normal shell.  Try using a full path in your crontab entry.

Thanks,
 Phil

**Comment by ngocthach** [comment]
Hi @philshafer ,
Thanks for your help
I have fix this problem, only edit path enviroment in jsnap file (which jsnap)

Thanks all
